using System.Runtime.Serialization;
using System.ServiceModel;

namespace CurrencyExchangeClient.Services
{
    // ── DATA CONTRACTS (mirror of server-side) ────────────────────────────────
    // In a real project these are auto-generated by "Add Service Reference".
    // We define them manually here so the project compiles without the running service.

    [DataContract]
    public class ExchangeRate
    {
        [DataMember] public string CurrencyCode { get; set; }
        [DataMember] public string CurrencyName { get; set; }
        [DataMember] public decimal MidRate { get; set; }
        [DataMember] public decimal BuyRate { get; set; }
        [DataMember] public decimal SellRate { get; set; }
        [DataMember] public DateTime EffectiveDate { get; set; }
    }

    [DataContract]
    public class ExchangeResult
    {
        [DataMember] public bool Success { get; set; }
        [DataMember] public string Message { get; set; }
        [DataMember] public string FromCurrency { get; set; }
        [DataMember] public string ToCurrency { get; set; }
        [DataMember] public decimal AmountSent { get; set; }
        [DataMember] public decimal AmountReceived { get; set; }
        [DataMember] public decimal RateUsed { get; set; }
        [DataMember] public DateTime Timestamp { get; set; }
    }

    // ── SERVICE CONTRACT (mirror of server-side IExchangeService) ─────────────

    [ServiceContract]
    public interface IExchangeService
    {
        [OperationContract] string Ping();
        [OperationContract] ExchangeRate GetRate(string currencyCode);
        [OperationContract] List<ExchangeRate> GetRates(List<string> currencyCodes);
        [OperationContract] List<ExchangeRate> GetAllRates();
        [OperationContract] List<ExchangeRate> GetHistoricalRates(string currencyCode, DateTime startDate, DateTime endDate);
        [OperationContract] ExchangeResult BuyCurrency(string currencyCode, decimal amountPln);
        [OperationContract] ExchangeResult SellCurrency(string currencyCode, decimal amountForeign);
    }

    // ── WCF CLIENT PROXY ──────────────────────────────────────────────────────

    /// <summary>
    /// WCF channel proxy — wraps the generated ChannelFactory.
    /// Use inside a using() block so the channel is always closed cleanly.
    /// </summary>
    public class ExchangeServiceClient : ClientBase<IExchangeService>, IExchangeService
    {
        public ExchangeServiceClient()
            : base("ExchangeServiceEndpoint") { }

        public string Ping()
            => Channel.Ping();

        public ExchangeRate GetRate(string currencyCode)
            => Channel.GetRate(currencyCode);

        public List<ExchangeRate> GetRates(List<string> currencyCodes)
            => Channel.GetRates(currencyCodes);

        public List<ExchangeRate> GetAllRates()
            => Channel.GetAllRates();

        public List<ExchangeRate> GetHistoricalRates(string currencyCode, DateTime startDate, DateTime endDate)
            => Channel.GetHistoricalRates(currencyCode, startDate, endDate);

        public ExchangeResult BuyCurrency(string currencyCode, decimal amountPln)
            => Channel.BuyCurrency(currencyCode, amountPln);

        public ExchangeResult SellCurrency(string currencyCode, decimal amountForeign)
            => Channel.SellCurrency(currencyCode, amountForeign);
    }
}
